version: '3.2'
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432
volumes:
  postgres:
